[package]
name = "deriva-compute"
version = "0.1.0"
edition = "2021"

[dependencies]
deriva-core = { path = "../deriva-core" }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
num_cpus = "1"
blake3 = "1"
sha2 = { workspace = true }
base64 = { workspace = true }
flate2 = { workspace = true }
crc32fast = { workspace = true }
prometheus = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
sled = { workspace = true }
